### ISSUE TITLE
video optical flow

### ISSUE THREAD

**Issue by sarmadm** [georgegach/flowiz#1]
HI

How can I get optical flow estimation for each frame from video file and save these images ?

**Comment by georgegach** [comment]
I use `ffmpeg` to extract frames from videos. Since I do it only once I didn't include it in the package, but here you go, a helpful snippet.
```
ffmpeg -i nfs_cut.mp4 -r 25.0 ./frames/nfs_frame%4d.png
```
Input framerate via `-r 25.0` flag. 
Also, make sure your output is `.png` or any other lossless image format since you are dealing with optical flow.

**Comment by georgegach** [comment]
Hi

This package is for converting flow fields to images. Flows are generated by optical flow models like [OpenCV/LucasKanade](https://docs.opencv.org/3.4/d7/d8b/tutorial_py_lucas_kanade.html), [NVIDIA/flownet2-pytorch](https://github.com/NVIDIA/flownet2-pytorch),  [NVLabs/PWC-Net](https://github.com/NVlabs/PWC-Net) and etc.

**Comment by sarmadm** [comment]
Thanks for replying , How can I install your library (flow2image)

Can I generate optical flow output for a video if the length is 1 or 2 minutes ?

**Comment by georgegach** [comment]
> Thanks for replying , How can I install your library (flow2image)

Sure, but I don't think it's what you need. This library is **not** for generating optical flow. It's for converting an already generated optical flow vector (u,v) into the images (r,g,b) that I created for my research to be similar to MPI Sintel visualizations. 

> Can I generate optical flow output for a video if the length is 1 or 2 minutes ?

If you want to generate an optical flow for some video, I think the simplest is to follow OpenCV's tutorial https://docs.opencv.org/3.4/d7/d8b/tutorial_py_lucas_kanade.html You can definitely generate 1-2 minutes of flow even on a laptop easily.  

I'll now close this issue. Feel free to open another if you have questions about this library.
