### ISSUE TITLE
AssertionError: Path [ ] does not exist

### ISSUE THREAD

**Issue by aoteman233** [georgegach/flowiz#17]
Thank you so much for your amazing work！I have this problem when I generate the video, do you know how to fix it？

![屏幕截图 2022-04-13 152016](https://user-images.githubusercontent.com/73416150/163122221-9ccf9567-0b16-4531-88dc-238d42e2218e.png)
Looking forward to your reply, thank you very much！

**Comment by georgegach** [comment]
It seems like `flowiz` wasn't able to read the last `flo` file from the list you gave. Did you perhaps remove it while it was still generating `png`s? Or perhaps some file permissions error.

**Comment by aoteman233** [comment]
Thank you very much, I have solved the problem, it seems to be the problem with the file path, thank you again for the amazing work
