### ISSUE TITLE
Insanely slow computation on convert_from_flow

### ISSUE THREAD

**Issue by ErenBalatkan** [georgegach/flowiz#3]
I have benchmarked the following method
```
        result = f.convert_from_flow(flow)
```
This takes around 0.4 seconds to execute, meanwhile opencv based manually written method

```
        hsv = numpy.zeros_like(frame)
        hsv[..., 1] = 255
        mag, ang = cv2.cartToPolar(flow[..., 0], flow[..., 1])
        hsv[..., 0] = ang * 180 / numpy.pi / 2
        hsv[..., 2] = cv2.normalize(mag, None, 0, 255, cv2.NORM_MINMAX)
        rgb = cv2.cvtColor(hsv, cv2.COLOR_HSV2RGB)
```
Takes around 0.03 seconds to execute.

I would like to use method of flowiz over opencv based one since generated image is much more pleasing but around 0.4 seconds per image is too slow.

**Comment by georgegach** [comment]
That's the cost of using Python and perhaps it makes sense to rewrite this into Cython. I'll look into local optimizations though, thanks.
