### ISSUE TITLE
How to realize the batch conversion

### ISSUE THREAD

**Issue by GUWOGANSHOU** [georgegach/flowiz#6]
`python -m flowiz demo/flo/000030.flo --outdir demo/png/`
I use this to convert one .flo file to .png.
But it is too slow for a large file to conver one by one.
How can i do to realize the batch conversion?

**Comment by georgegach** [comment]
So did you try glob syntax and it didn't work? 
```
python -m flowiz demo/flo/*.flo --outdir demo/png/
```
Alternatively just open up jupyter notebook and do it programatically
```
import flowiz as fz

files = glob.glob('demo/flo/*.flo')
img = fz.convert_from_file(files[0])
```
It's in the readme
