### ISSUE TITLE
Hue and color intensity

### ISSUE THREAD

**Issue by Aithusa1113** [georgegach/flowiz#9]
Hi, can it show how hue and color intensity direction relationship with magnitude of the displacement vector? I cannot distinguish which color represents higher magnitude.

**Comment by georgegach** [comment]
In HSV color representation terms, the saturation is the component proportional to the magnitude of the displacement vector. In other terms lighter the color looks lower the magnitude it represents. 

This image from `flowiz.gui` should be helpful in interpreting the results representing XY vector space. 

The color points closer to the center (0,0) represent displacement vectors with lower magnitude with respective directions. 
 
 
![colormap](https://raw.githubusercontent.com/georgegach/flowiz/master/flowiz/gui/web/assets/rgb.jpg)
